add_newline = true
command_timeout = 200
format = """
[$directory$git_branch$git_status]($style)
 $character """

[character]
success_symbol = "[■](#ed6a5a)[■](#f4f1bb)[■](#58ada2)"
error_symbol   = "[■](#ed6a5a)[■](#f4f1bb)[■](#58ada2)"


[directory]
truncation_length = 0
home_symbol = "~"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "italic #FF8800"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "?${count} "
modified   = "✎ ${count} "
stashed    = ""
staged     = "+${count} "
renamed    = ""
deleted    = "✖${count} "
